version: 0.1.0-{build}-{branch}

assembly_info:
  patch: false

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

nuget:
  account_feed: true
  project_feed: true

install:
  - cinst stylecop
