version: 0.1.0-{build}-{branch}

assembly_info:
  patch: false

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

nuget:
  account_feed: true
  project_feed: true

install:
  # - cinst stylecop
  - cinst psake
  - cinst 7zip.commandline
  - gem update --system
  - gem install asciidoctor --no-document

after_build:
  - psake Build-Artifacts

artifacts:
  - path: artifacts\gomer.zip
  - path: artifacts\README.html
