= Gomer
Aaron Dorheim-Davis, <https://github.com/recfab[@recfab]>
:revnumber: 1.1.0-pre
:revdate: 2015-01-20
:fonts: icon
:nofooter:
:toc:
:toc-placement: preamble
:repo: https://github.com/recfab/Gomer
:repo-link: {repo}/tree/master
:ci-link: https://ci.appveyor.com/project/recf/gomer
:ci-img: https://ci.appveyor.com/api/projects/status/oei3gded2b0h9q36?svg=true

image::{ci-img}[alt=Build Status, link={ci-link}]

Gomer is a small utility for managing your video game "pile".

Pile data is saved in a JSON file with the .pile extension. The JSON Schema of
the file can be found at link:{repo-link}/doc/schemas[].

There is no installer currently, so to use it, just extract the contents of the
zip file somewhere on your system and double-click gomer.exe.

== TODO

* `Psake` task to patch the version in this README file.
* `Psake` task to patch the date in this README file.
* `Psake` task to patch the version in appveyor.yml
* Look into Awestruct for generating gh-pages. That's what asciidoctor.org uses.
* Localization
* Better test coverage (i.e. any)
* The ability to make custom lists of games. It's nice to sort by platform or by status, but I wanted to make lists like, "Games to finish before I start Xenoblade", or even just, "Atlus RPGs".
** Hide lists
** whether to include in stats
* Set multiple platforms per game
* Custom status markers. "Beaten" and "Unfinished" are nice, but I never cared about "Completed" and "Null" didn't do what I want. What about "New Game+" or "Replay" or "Screw This Game"? That would also help the problem of not having a status for games you've given up on that's not just deleted.
* Playthrough information: Status, Start Date, Finish Date, Note
* A flag for whether I own a game on disc/cartridge or digitally.
* The ability to assign multiple platforms to a game but track it as a single game. Like, if I have Shovel Knight on both Wii U and 3DS, and I beat it on one of those, mark it as beaten on both.

=== From Source

include::Source-TODO.adoc[leveloffset=+1]
